version: '2'
services:
  router:
    container_name: router
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./webapp:/usr/share/nginx/html
    network_mode: "host"
